version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install system prerequisites
          command: |
            sudo apt-get update
            sudo apt-get install make -y
      - run:
          name: Install Database Factory
          command: |
            pip install .
      - run:
          name: Install test dependency
          command: |
            pip install coverage==7.2.3 exceptiongroup==1.1.1 iniconfig==2.0.0 pluggy==1.0.0 pytest==7.3.0 pytest-cov==4.0.0 tomli==2.0.1
      - run:
          name: Test Database Factory
          command: |
            pytest -v --cov --cov-report html --cov-report xml --junitxml=test-results/database_factory_test/results.xml
      - store_artifacts:
          path: htmlcov/
          destination: coverage/html
      - store_artifacts:
          path: coverage.xml
          destination: coverage/coverage.xml
      - store_test_results:
          path: test-results
workflows:
  main:
    jobs:
      - build-and-test
